// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:563828992145:web:26eaf35450f9de7a88b730',
    messagingSenderId: '563828992145',
    projectId: 'staj-c173e',
    authDomain: 'staj-c173e.firebaseapp.com',
    storageBucket: 'staj-c173e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:563828992145:android:05cae1d39813992a88b730',
    messagingSenderId: '563828992145',
    projectId: 'staj-c173e',
    storageBucket: 'staj-c173e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:563828992145:ios:ae3125512714982f88b730',
    messagingSenderId: '563828992145',
    projectId: 'staj-c173e',
    storageBucket: 'staj-c173e.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:563828992145:ios:ae3125512714982f88b730',
    messagingSenderId: '563828992145',
    projectId: 'staj-c173e',
    storageBucket: 'staj-c173e.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:563828992145:web:a94e324b44e6f80e88b730',
    messagingSenderId: '563828992145',
    projectId: 'staj-c173e',
    authDomain: 'staj-c173e.firebaseapp.com',
    storageBucket: 'staj-c173e.appspot.com',
  );
}
